on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: diary
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true
      - name: Build hugo
        run: |
          hugo --minify
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: setup metadata 
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/homirun/diary
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss'}}
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: ${{ steps.meta.outputs.tags }}